### ISSUE TITLE
teeworlds.com website is down

### ISSUE THREAD

**Issue by pelya** [teeworlds/teeworlds#1495]
I would complain on the forum, but the forum is down too.

**Comment by heinrich5991** [comment]
Known issue. Hardware failure. @minus7 Maybe you could put up a "currently down" website?

**Comment by minus7** [comment]
Done

**Comment by Tardo** [comment]
The end of teeworlds or the first issue closed in years? what will happen?

**Comment by pelya** [comment]
They did not fix the issue yet, they just put up a stub webpage.

On Jun 4, 2017 2:49 AM, "QS5ELkMu" <notifications@github.com> wrote:

The end of teeworlds or the first issue closed in years? what will happen?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/teeworlds/teeworlds/issues/1495#issuecomment-306008300>,
or mute the thread

**Comment by minus7** [comment]
It should be back by tuesday.

**Comment by Tardo** [comment]
Nope. :nerd_face:

**Comment by pelya** [comment]
By last Tuesday of the next month, obviously.

**Comment by minus7** [comment]
God, I hate PHP. Website is back.

**Comment by pelya** [comment]
Yaay!

**Comment by Tardo** [comment]
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks:
